#!/bin/bash

cd guiding_center_solver/build
cmake ..
cmake --build .

cd ../..
cp guiding_center_solver/build/Solver Lab/Example/
cp guiding_center_solver/build/Diagnosor Lab/Example/

cd Lab/Example
./Solver
./Diagnosor